import 'package:hive/hive.dart';

part 'pet_hive_model.g.dart';  // This file will be generated by Hive

@HiveType(typeId: 0)
class Pet {
  @HiveField(0)
  final String name;
  @HiveField(1)
  final int age;
  @HiveField(2)
  final double price;
  @HiveField(3)
  final String imageUrl;
  @HiveField(4)
  bool isAdopted;

  Pet({required this.name, required this.age, required this.price, required this.imageUrl, this.isAdopted = false});
}
